# Generated by Django 4.2.7 on 2023-11-18 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_brand_product_color_product_size_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
