# Generated by Django 4.2.7 on 2023-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_change_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chart_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productline',
            name='chart_change',
            field=models.BooleanField(default=False),
        ),
    ]
